### ISSUE TITLE
[Feature request] Ukrainian translation

### ISSUE THREAD

**Issue by vkaraiev** [zeddoth/S2HOC_FactionPatch#1]
Great job on the mod!

I made a Ukrainian translation, it is grammatically and lore- correct: [FactionsPatch_UA.json](https://github.com/user-attachments/files/18029528/FactionsPatch_UA.json)

Would be great if you could include it!

**Comment by zeddoth** [comment]
I will add the translation with the next update, **thank a lot for your contribution !**
